PIN_ROOT ?= $(error Set PIN_ROOT to your PIN installation directory)

include $(PIN_ROOT)/source/tools/Config/makefile.config
TOOL_ROOTS := prot_count
include $(PIN_ROOT)/source/tools/Config/makefile.rules
